### ISSUE TITLE
needs for Mar 2 testing

### ISSUE THREAD

**Issue by esalling23** [ExtraLudic/Daedalus_Tamagachi#29]
- get rid of timer
- input other than good input makes warmth go down
- Temp Control:
   - Sun or Partly Sun: +1 heat
   - Cloud or mostly cloud: -1 Heat
   - Rain: -2 Heat
   - Hot Springs: +2 heat
   - Fire: +3 heat
   - Snow: -3 Heat
   - Snowman: -3 Heat
   - Lightbulb: +1 heat per lightbulb in the string
- need to hit 85% - hatch and win

no food or poops for now

**Comment by wadek2** [comment]
Yes this looks good.
